### ISSUE TITLE
Move the package to a GitHub organisation?

### ISSUE THREAD

**Issue by core77** [Foundation-for-Jekyll-sites/jekyll-foundation#53]
What do you think about moving this package to a GitHub organisation?

I think it would improve the maintaining of the project and it could be developed in the right direction, doing stuff that you - the users - need.

**Any naming suggestions for the organisation?** 

Since the package was updated to Foundation 6.4 by @kculmback and tested by @huphtur I suggest them to be **members** of the new organisation.

**Comment by kculmback** [comment]
@core77 I would be happy to be a member of a Github organization for this project! I use this repo as a basis for my own website, so I have a vested interest in making sure it's up to date!

**Comment by huphtur** [comment]
Sounds good with me. I'm using the repo for work. So will have to stay on top of things. 

@core77: since it's your baby you get the honors in naming it 😉 

BTW is core77 related to core77.com?

**Comment by andycochran** [comment]
"Foundation for Sites for Jekyll" 😄

**Comment by andycochran** [comment]
@kball might have thoughts on this.

**Comment by huphtur** [comment]
Foundation for Jekyll sites?

**Comment by core77** [comment]
Not related to core77.com...

**Comment by core77** [comment]
On holidays right now... post your suggestions here. I thought about asking the ZURB people because there's more foundation in here than Jekyll. I'll take a look at this topic when I'm back ;-)

**Comment by core77** [comment]
Ok, we have the suggestions

- Foundation for Jekyll sites
- Foundation for Sites for Jekyll

As I can see, finding a proper name is not so easy :-o

What do you think about
- JF
- twrk (teamwork, a more generic name...)
- jekyll-foundation

My favorite is "Foundation for Jekyll sites".

**Comment by IamManchanda** [comment]
**Fantastico!!!** 

PS: If you would like to add me in the org and contribute, then let me know coz i like it :) 
Thanks, 
Harry Manchanda, **YETINAUT**

**Comment by kculmback** [comment]
I would second "Foundation for Jekyll sites"

**Comment by goodtimeclub** [comment]
I THIRD "Foundation for Jekyll sites" 😂

**Comment by IamManchanda** [comment]
Foundation for Jekyll sites ... I don't think is the right choice.
Fantastico is a good name if you want to choose :D

**Comment by core77** [comment]
@IamManchanda There is still some time for votes... If there are supporters, why not :-)

**Comment by core77** [comment]
Done.
