### ISSUE TITLE
[Pagination] Page 1 link broken

### ISSUE THREAD

**Issue by andycochran** [Foundation-for-Jekyll-sites/jekyll-foundation#54]
I thought this might be related to a typo on [index.html line 35](https://github.com/core77/jekyll-foundation/blob/fb995cb6003401a1216ed4b61298dbe54a6e0087/blog/index.html#L35): 

`'/seite:num'`

^ Should this be `'/site:num'` or `'/page:num'`? 

I've tried both. But the page 1 URL (when on other pages) is still set as `http://127.0.0.1.xip.io:3000/blog/page:num`.

**Comment by andycochran** [comment]
Also, per [Foundation docs](http://foundation.zurb.com/sites/docs/pagination.html), the current page does not need the `<a>` tag. 

I've replaced lines 33-35 with the following, which works for me. 

```
...
    <li class="current">{{ page }}</li>
{% elsif page == 1 %}
    <li><a href="{{ site.baseurl }}/blog/">{{ page }}</a></li>
...
```

I can PR if you like this change.

**Comment by kculmback** [comment]
I think I have fixed the issue you are having. I changed the markup to directly match what is suggested on the jekyll website, which seems to be working.

I'll submit a pull request, but it may be worth testing before it's committed. You can find the code [here](https://github.com/kculmback/jekyll-foundation/blob/paginate/blog/index.html). @core77 do you want to take a look at this as well?

It should be worth noting that this also utilizes the plugin setup I mentioned here #55

**Comment by core77** [comment]
If this is resolved through kckulmback's PR, would someone close this? I have only iOS devices around me and no possibility to test :-(

**Comment by kculmback** [comment]
Closed since there seems to be no further issues!
