### ISSUE TITLE
[Config] plugins_dir & pagination error

### ISSUE THREAD

**Issue by andycochran** [Foundation-for-Jekyll-sites/jekyll-foundation#55]
When getting started, I had to change `plugins` to `plugins_dir` and add the `jekyll-paginate` gem in `_config.yml`. 

https://github.com/NYCPlanning/foundation-planninglabs.nyc/commit/73d88db7d613e28c2c03c63c521af39a5f327fe6 

Should I PR this?

**Comment by kculmback** [comment]
Thanks for bringing this up @andycochran, I was actually recently thinking about this. As far as my understanding goes, we only need to include plugins in one place, as per the instructions on the [jekyll website](https://jekyllrb.com/docs/plugins/). Maybe it would be best to just use one of these methods?

Including them just in the Gemfile seems to be popular. We could switch the Gemfile to the following:
```
group :jekyll_plugins do
	gem 'jekyll', '>=3.0'
	gem 'sass'
	gem 'jekyll-sitemap'
	gem 'jekyll-paginate'
end
```

Thoughts? @core77

**Comment by core77** [comment]
If this is resolved through kckulmback's PR, would someone close this? I have only iOS devices around me and no possibility to test :-(

**Comment by kculmback** [comment]
Closing since there seems to be no further issues!
