### ISSUE TITLE
Linux: Error in plugin 'run-sequence(watch) 

### ISSUE THREAD

**Issue by core77** [Foundation-for-Jekyll-sites/jekyll-foundation#67]
I'm getting an error. I think it's linux related. 

`Error in plugin 'run-sequence(watch)'

Message:
    watch /home/chris/dev/jekyll-foundation/ ENOSPC
`

Any ideas?

**Comment by huphtur** [comment]
[According to SO](https://stackoverflow.com/questions/22475849/node-js-error-enospc) it's a disk full error.

**Comment by core77** [comment]
Recloned the repo an then it worked :-)
