### ISSUE TITLE
The _foundation.scss differs from Zurb's in 6.4.3. Is this intentional?

### ISSUE THREAD

**Issue by captaincoffee** [Foundation-for-Jekyll-sites/jekyll-foundation#68]
It looks significantly different to me. For example, in Zurb's 6.4.3 the x-y grid is the default, while in jekyll-foundation, the flex grid is default. There are other differences. I'm no expert, so it may be irrelevant. Just asking.

**Comment by core77** [comment]
It should be almost the same as Zurb uses in their  [foundation-zurb-template](https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/scss/app.scss). There they use the panini static site generator.

You can do awesome stuff with the xy-grid (checkout the video in their docs). Therefore don't include the grid, don't include the flex-grid but include the xy-grid-classes as they do in the linked app.scss (see above).

**Comment by captaincoffee** [comment]
Thank you.
